version: 2
jobs:
  build:
    working_directory: ~/repo
   

    environment:
      # Customize the JVM maximum heap limit
      _JAVA_OPTIONS: -Xms128m -Xmx512m
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results

    docker:
      # specify the version you desire here
      - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37

    steps:
      # Machine Setup
      - checkout
      - run:
          name: Creating temp directories
          command: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          name: Update java alternatives
          working_directory: ~/repo
          command: sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java; sudo update-alternatives --set javac /usr/lib/jvm/java-8-openjdk-amd64/bin/javac; echo -e "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $BASH_ENV

      # Download and cache dependencies
     
        
      # run full testing 

      - run: mkdir -p $CIRCLE_TEST_REPORTS/munit/